[colors]
ansi = [
    '#efeff2',
    '#a01010',
    '#106710',
    '#60400f',
    '#103077',
    '#700d50',
    '#005355',
    '#000000'
]
brights = [
    '#efeff2',
    '#a01010',
    '#106710',
    '#60400f',
    '#103077',
    '#700d50',
    '#005355',
    '#000000'
]
cursor_bg = '#2266bb'
cursor_border = '#2266bb'
cursor_fg = '#ffffff'
background = '#ffffff'
foreground = '#000000'
selection_bg = '#a0bcd0'
selection_fg = '#000000'

[metadata]
name = 'Doric-Light'
author = 'anhsirk0'
origin_url = 'https://codeberg.org/anhsirk0/wezterm-themes/src/branch/main/colors/doric-light.toml'
