[colors]
ansi = [
    '#e5dde0',
    '#a00040',
    '#006730',
    '#704000',
    '#203080',
    '#800060',
    '#005560',
    '#35292f'
]
brights = [
    '#e5dde0',
    '#a00040',
    '#006730',
    '#704000',
    '#203080',
    '#800060',
    '#005560',
    '#35292f'
]
cursor_bg = '#a02050'
cursor_border = '#a02050'
cursor_fg = '#f7edf1'
background = '#f7edf1'
foreground = '#35292f'
selection_bg = '#cc95b7'
selection_fg = '#35292f'

[metadata]
name = 'Doric-Cherry'
author = 'anhsirk0'
origin_url = 'https://codeberg.org/anhsirk0/wezterm-themes/src/branch/main/colors/doric-cherry.toml'
