[colors]
ansi = [
    '#40332b',
    '#eca27f',
    '#b9d08a',
    '#c5ba80',
    '#9fbfe7',
    '#e9acbf',
    '#a0c0d0',
    '#f5ceb0'
]
brights = [
    '#40332b',
    '#eca27f',
    '#b9d08a',
    '#c5ba80',
    '#9fbfe7',
    '#e9acbf',
    '#a0c0d0',
    '#f5ceb0'
]
cursor_bg = '#ef7839'
cursor_border = '#ef7839'
cursor_fg = '#282420'
background = '#282420'
foreground = '#f5ceb0'
selection_bg = '#7c362c'
selection_fg = '#f5ceb0'

[metadata]
name = 'Doric-Fire'
author = 'anhsirk0'
origin_url = 'https://codeberg.org/anhsirk0/wezterm-themes/src/branch/main/colors/doric-fire.toml'
