[colors]
ansi = [
    '#dfdfce',
    '#a03000',
    '#206700',
    '#705200',
    '#103060',
    '#690f44',
    '#105f66',
    '#30232e'
]
brights = [
    '#dfdfce',
    '#a03000',
    '#206700',
    '#705200',
    '#103060',
    '#690f44',
    '#105f66',
    '#30232e'
]
cursor_bg = '#770000'
cursor_border = '#770000'
cursor_fg = '#f0eddf'
background = '#f0eddf'
foreground = '#30232e'
selection_bg = '#c09fa0'
selection_fg = '#30232e'

[metadata]
name = 'Doric-Earth'
author = 'anhsirk0'
origin_url = 'https://codeberg.org/anhsirk0/wezterm-themes/src/branch/main/colors/doric-earth.toml'
