[colors]
ansi = [
    '#302f3c',
    '#eca28f',
    '#b9d0aa',
    '#c0b080',
    '#9fbfe7',
    '#e9acbf',
    '#a0c0d0',
    '#e2d7e7'
]
brights = [
    '#302f3c',
    '#eca28f',
    '#b9d0aa',
    '#c0b080',
    '#9fbfe7',
    '#e9acbf',
    '#a0c0d0',
    '#e2d7e7'
]
cursor_bg = '#c070d0'
cursor_border = '#c070d0'
cursor_fg = '#221832'
background = '#221832'
foreground = '#e2d7e7'
selection_bg = '#5e4170'
selection_fg = '#e2d7e7'

[metadata]
name = 'Doric-Plum'
author = 'anhsirk0'
origin_url = 'https://codeberg.org/anhsirk0/wezterm-themes/src/branch/main/colors/doric-plum.toml'
