[colors]
ansi = [
    '#332d38',
    '#eca28f',
    '#b9d0aa',
    '#c0b080',
    '#9fbfe7',
    '#e9acbf',
    '#a0c0d0',
    '#ffffff'
]
brights = [
    '#332d38',
    '#eca28f',
    '#b9d0aa',
    '#c0b080',
    '#9fbfe7',
    '#e9acbf',
    '#a0c0d0',
    '#ffffff'
]
cursor_bg = '#ccaaee'
cursor_border = '#ccaaee'
cursor_fg = '#000000'
background = '#000000'
foreground = '#ffffff'
selection_bg = '#50447f'
selection_fg = '#ffffff'

[metadata]
name = 'Doric-Dark'
author = 'anhsirk0'
origin_url = 'https://codeberg.org/anhsirk0/wezterm-themes/src/branch/main/colors/doric-dark.toml'
