[colors]
ansi = [
    '#2f2f2f',
    '#eca28f',
    '#b9d0aa',
    '#c0b080',
    '#9fbfe7',
    '#e9acbf',
    '#a0c0d0',
    '#e7e7e7'
]
brights = [
    '#2f2f2f',
    '#eca28f',
    '#b9d0aa',
    '#c0b080',
    '#9fbfe7',
    '#e9acbf',
    '#a0c0d0',
    '#e7e7e7'
]
cursor_bg = '#eeddbb'
cursor_border = '#eeddbb'
cursor_fg = '#181818'
background = '#181818'
foreground = '#e7e7e7'
selection_bg = '#505050'
selection_fg = '#e7e7e7'

[metadata]
name = 'Doric-Obsidian'
author = 'anhsirk0'
origin_url = 'https://codeberg.org/anhsirk0/wezterm-themes/src/branch/main/colors/doric-obsidian.toml'
