[colors]
ansi = [
    '#291f26',
    '#ff7359',
    '#60b444',
    '#e5b76f',
    '#8fa5f6',
    '#ef80bf',
    '#8fbaef',
    '#d3cfcf'
]
brights = [
    '#594a4f',
    '#ff78aa',
    '#60bf88',
    '#f59280',
    '#7fa5ff',
    '#df7fff',
    '#8fcfdf',
    '#808898'
]
cursor_bg = '#ff5aaf'
cursor_border = '#ff5aaf'
cursor_fg = '#190a0f'
background = '#190a0f'
foreground = '#d3cfcf'
selection_bg = '#232f3f'
selection_fg = '#d3cfcf'

[metadata]
name = 'Ef-Cherie'
author = 'anhsirk0'
origin_url = 'https://git.sr.ht/~protesilaos/ef-themes/tree/main/item/ef-cherie-theme.el'
