[colors]
ansi = [
    '#efe9dd',
    '#a60000',
    '#006800',
    '#6f5500',
    '#0031a9',
    '#721045',
    '#005e8b',
    '#000000'
]
brights = [
    '#c9b9b0',
    '#a0132f',
    '#00663f',
    '#7a4f2f',
    '#0000b0',
    '#531ab6',
    '#005f5f',
    '#595959'
]
cursor_bg = '#dfa0f0'
cursor_border = '#dfa0f0'
cursor_fg = '#fbf7f0'
background = '#fbf7f0'
foreground = '#000000'
selection_bg = '#c2bcb5'
selection_fg = '#000000'

[metadata]
name = 'Modus-Operandi-Tinted'
author = 'anhsirk0'
origin_url = 'https://git.sr.ht/~protesilaos/ef-themes/tree/main/item/modus-operandi-tinted-theme.el'
